### ISSUE TITLE
No module named argparse

### ISSUE THREAD

**Issue by jalanb** [jwcxz/vim-pandemic#3]
$ pandemic update
Traceback (most recent call last):
  File "/usr/local/bin/pandemic", line 3, in <module>
    import argparse, ConfigParser, os, sys
ImportError: No module named argparse

$ python --version
Python 2.6.5

Turns out argparse was only added in python 2.7 (and 3.2). This is not an unreasonable dependency, but I think the readme should state that pandemic's minimal requirements for python.

And they should be added to the setup.py

**Comment by jwcxz** [comment]
According to the internet (i.e. I've never tried this myself, so I apologize if it turns out to be false), you can get argparse for <2.7 [on PyPI](https://pypi.python.org/pypi/argparse).  So, I added `requires=["argparse"]` to the setup script.  This should prevent the installer from installing pandemic until the requirement is met.

Thanks for reporting this!

Edit: feel free to re-open if this does not actually solve the problem.
